brew 'coreutils'
brew 'ghq'
brew 'hg'
brew 'git'
brew 'openssl'
brew 'peco'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'highlight'
brew 'hey'
brew 'jq'
brew 'gotags'
brew 'ctags'
brew 'stern'
brew 'minikube'
brew 'htop'
brew 'ag'
brew 'hub'
brew 'asdf'
brew 'vault'
brew 'gnupg'
brew 'watch'
# https://qiita.com/ykgeek/items/98ecfd0f3e22cea7eb10
brew 'pinentry-mac'
brew 'findutils'
brew 'fzf'
brew 'pstree'
brew 'k9s'
brew 'kubectx'

cask 'docker'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'spectacle'
cask 'google-backup-and-sync'
cask 'google-cloud-sdk'
cask 'stay'
cask '1password-cli'

tap 'homebrew/cask-fonts'
cask 'font-devicons'
cask 'font-fontawesome'
cask 'font-noto-sans'
cask 'font-noto-sans-cjk-jp'
cask 'font-noto-serif'
cask 'font-hack'

tap 'sanemat/font'
# After installing ricty, execute the following commands:
# $ cp -f $(brew --prefix ricty)/share/fonts/Ricty*.ttf ~/Library/Fonts/
# $ fc-cache -vf
brew 'ricty', args: ['with-powerline']
# vim: set ft=ruby :
