alias ls='ls -G'
alias ll='ls -lhFG'
alias la='ls -ahFG'
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias svim='sudo vim'
alias r='rails'
alias b='bundle'
alias bi='bundle install'
alias bu='bundle update'
alias bl='bundle list'
alias be='bundle exec'
alias bc='bundle console'
alias nb='nodebrew'
if [[ -x `which -p hub` ]]; then
    alias git='hub'
fi
alias g='git'
alias gs='git status -sb'
